# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true


# Setup
title:            Archblog
tagline:          blog
description:      'blog about Archlinux, javascript, Laravel, and more'
url:              http://drog.github.io
baseurl:          /
analytics: UA-45813922-4

author:
  name:           drog
  url:            http://drog.github.io
  email:          dreg27@gmail.com
  github:         https://github.com/drog			
paginate:         5

github:
  repo:           https://github.com/drog/drog.github.io

disqus:
    shortname: 'httpdroggithubio'

excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
